### PR TITLE
Add limit feature

### PR DESCRIPTION
**Pull request by escudero89**
With this PR, I am trying to add a `limit` feature that will trim the rows until a certain `limit` (if defined, otherwise it will work as usual).

Our use-case is a monorepo, in where many people work, and the table grows quite big.

Added test-case and ran the build action (which introduces changes that I did not make but were previously in the master branch).

### CODE REVIEW

**Review by manuelmhtr — APPROVED** [review]

**Comment by manuelmhtr** [comment]
Hi @escudero89 
Thanks for your contribution! changes are now available in [v2.1.0](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.1.0).

**Comment by escudero89** [comment]
Hi @manuelmhtr, I think I introduced a bug though with the feature 😢 . Could it be that the number of totalReviews are being shorten? I don't quite know why by just reading the code. Or is it working correctly?

Also a nice feature would be to not add the table if it finds that the `# Pull reviewers stats` text is already in the description (because otherwise it keeps replicating the table, e.g. by opening and closing the PR)

**Comment by manuelmhtr** [comment]
Hi @escudero89 that's true. I didn't see the bug either, no problem. Since it only happens when the limit option is enabled it won't happen a lot (for now). I'll fix it as soon as possible.

About the table being replicated, indeed that's the intended behavior. However, there was a bug, when the PR description was empty the table is printed up to 2 times. That was fixed before but as you noticed some changes were not included in the build. It should be fixed in v2.1.0 now.

**Comment by manuelmhtr** [comment]
Hey @escudero89 the bug is fixed now in [v2.1.1](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.1.1). Thanks for reporting it!

**Comment by escudero89** [comment]
Gracias Manu :)

**Pull request closed without merging**
